package unisolar.api.domain.dto.energy;

/**
 * Data Transfer Object (DTO) representing details of a solar panel.
 * Used for transferring solar panel data between different layers of the application.
 *
 * @param id                     the unique identifier of the solar panel.
 * @param location               the physical location or placement of the solar panel (e.g., "Roof").
 * @param currentPowerGeneration the current power generation of the solar panel in relevant units (e.g., kW).
 * @param totalPowerGenerated    the total power generated by the solar panel since installation in relevant units (e.g., kWh).
 * @param efficiency             the efficiency of the solar panel as a percentage or decimal value.
 * @param status                 the operational status of the solar panel (e.g., "Operational").
 */
public record SolarPanelDTO(
        Long id,
        String location,
        double currentPowerGeneration,
        double totalPowerGenerated,
        double efficiency,
        String status
) {}
