package unisolar.api.domain.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Entity class representing an installation in the system.
 * This class is mapped to the "installations" table in the database.
 *
 * @param id                    the unique identifier of the installation.
 * @param user                  the user associated with this installation.
 * @param solarPanels           the list of solar panels associated with this installation.
 * @param battery               the battery associated with this installation.
 * @param installationDate      the date and time when the installation was created.
 * @param status                the operational status of the installation (e.g., "Active", "Inactive").
 * @param totalPowerGenerated   the total amount of power generated by the installation.
 * @param totalEnergySaved      the total amount of energy saved by the installation.
 *
 * This entity represents an installation that consists of solar panels, a battery, and is linked to a user.
 * It captures essential information like installation date, status, and the energy metrics generated by the system.
 */
@Entity
@Table(name = "installations")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class Installation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;

    @OneToMany(mappedBy = "installation")
    private List<SolarPanel> solarPanels;

    @OneToOne(mappedBy = "installation")
    private Battery battery;

    private LocalDateTime installationDate;
    private String status;
    private double totalPowerGenerated;
    private double totalEnergySaved;
}
