package unisolar.api.domain.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity class representing a solar panel in the system.
 * This class is mapped to the "solar_panels" table in the database.
 *
 * @param id                    the unique identifier of the solar panel.
 * @param location              the location where the solar panel is installed.
 * @param currentPowerGeneration the current power generation by the solar panel (in watts).
 * @param totalPowerGenerated   the total amount of power generated by the solar panel (in kilowatt-hours).
 * @param efficiency            the efficiency of the solar panel in generating power.
 * @param status                the operational status of the solar panel (e.g., "Operational", "Faulty").
 * @param installation          the installation that the solar panel is part of.
 *
 * This entity represents a solar panel within a larger installation, capturing key attributes
 * like power generation, efficiency, and status. It is linked to the installation entity,
 * indicating where the panel is located.
 */
@Entity
@Table(name = "solar_panels")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class SolarPanel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String location;

    private double currentPowerGeneration;

    private double totalPowerGenerated;

    private double efficiency;

    private String status;

    @ManyToOne
    @JoinColumn(name = "installation_id")
    private Installation installation;
}
